'use client'
import Link from 'next/link'
import {useEffect,useState} from 'react'
import type {SiteContent} from '@/lib/content/types'
import {SiteFooter} from '@/components/site-footer'
type Lang='vi'|'en'; type Kind='work'|'films'|'about'|'contact'|'filmDetail'

export function InnerPageView({content,page}:{content:SiteContent;page:Kind}){
 const [lang,setLang]=useState<Lang>('vi'),[menu,setMenu]=useState(false), project=content.featuredProjects[0], data=content.pages[page]
 useEffect(()=>{document.documentElement.lang=lang},[lang])
 return <div className={`inner-page ${page==='filmDetail'?'film-detail':`${page}-page`}`}><header className="nav nav-inner"><Link className="brand" href="/"><span>403</span><small>{content.brandDescriptor}</small></Link><div className="nav-meta">{data.meta[lang]}</div><nav>{content.navigation.map(i=><Link className={page===i.href.slice(1)||(page==='filmDetail'&&i.href==='/films')?'active':''} href={i.href} key={i.href}>{i.label[lang]}</Link>)}<LangButton lang={lang} setLang={setLang}/></nav><button className="menu-button" aria-label={menu?'Đóng menu':'Mở menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}><span/><span/><span/></button></header>
 <main>{page==='work'&&<Work c={content} l={lang}/>} {page==='films'&&<Films c={content} l={lang}/>} {page==='about'&&<About c={content} l={lang}/>} {page==='contact'&&<Contact c={content} l={lang}/>} {page==='filmDetail'&&project&&<Film c={content} l={lang}/>}</main>
 <SiteFooter brand={content.brand} descriptor={content.brandDescriptor} email={content.contact.email} navigation={content.navigation} footer={content.footer} language={lang}/>
 <div className={`mobile-menu ${menu?'open':''}`}>{content.navigation.map(i=><Link href={i.href} key={i.href}>{i.label[lang]}</Link>)}<LangButton lang={lang} setLang={setLang}/></div></div>
}
function LangButton({lang,setLang}:{lang:Lang;setLang:(l:Lang)=>void}){return <button className="lang-toggle" onClick={()=>setLang(lang==='vi'?'en':'vi')}>{lang==='vi'?'EN':'VI'}</button>}
function Card({c,l,film=false}:{c:SiteContent;l:Lang;film?:boolean}){const p=c.featuredProjects[0];return p?<Link className="work-item wide" data-cursor="VIEW" href={`/films/${p.slug}`}><div className={`work-art ${film?'art-crossroads':'art-light'}`}><b>{film?p.year:'01'}</b>{film?<span className="crossroads-lines"/>:<span className="art-figure"/>}</div><div><h2>{p.title} / {p.subtitle}</h2><p>{film?c.pages.films.projectGenre[l]:p.category[l]}{film?'':` · ${p.year}`}</p></div></Link>:null}
function Work({c,l}:{c:SiteContent;l:Lang}){const d=c.pages.work,p=c.featuredProjects[0];return <><section className="work-intro"><div><span>{d.kicker[l]}</span><span>{p?.year}</span></div><h1>{d.heading[l]}</h1><div className="work-filter">{d.filters.map((x,i)=><button className={i===0?'active':''} key={x.en}>{x[l]}</button>)}</div></section><section className="work-index"><Card c={c} l={l}/></section><Cta label={d.nextLabel[l]} text={d.nextLink[l]} href="/films"/></>}
function Films({c,l}:{c:SiteContent;l:Lang}){const d=c.pages.films;return <><section className="work-intro films-intro"><div><span>{d.kicker[l]}</span><span>{d.subKicker[l]}</span></div><h1>{d.heading[l]}</h1><p className="films-copy">{d.intro[l]}</p></section><section className="work-index films-index"><Card c={c} l={l} film/></section><Cta label={d.ctaLabel[l]} text={d.ctaLink[l]} href="/films/crossroads"/></>}
function About({c,l}:{c:SiteContent;l:Lang}){const d=c.pages.about;return <><section className="page-hero about-hero"><div className="page-kicker preserve-lines">{d.kicker[l]}</div><h1>{d.heading[l]}</h1><div className="page-hero-foot"><p>{d.heroCopy[l]}</p><span>{d.established[l]}</span></div></section><section className="editorial-section light-section"><div className="section-label">{d.viewpointLabel[l]}</div><div className="editorial-grid"><h2 className="preserve-lines">{d.viewpointHeading[l]}</h2><div className="body-copy">{d.paragraphs.map(x=><p key={x.en}>{x[l]}</p>)}</div></div></section><section className="beliefs"><div className="section-label">{d.teamLabel[l]}</div>{d.team.map((x,i)=><div className="belief-row" key={x.name}><span>0{i+1}</span><h3>{x.name}</h3><p>{x.role[l]}</p></div>)}<div className="section-label about-capabilities-label">{d.capabilitiesLabel[l]}</div>{c.services.map((x,i)=><div className="belief-row" key={x.title.en}><span>0{i+1}</span><h3>{x.title[l]}</h3><p>{x.description[l]}</p></div>)}</section><Cta label={d.nextLabel[l]} text={d.nextLink[l]} href="/work"/></>}
function Contact({c,l}:{c:SiteContent;l:Lang}){const d=c.pages.contact;return <><section className="contact-hero"><div className="contact-availability"><i/><span className="preserve-lines">{d.availability[l]}</span></div><h1>{d.heading[l]}</h1><a className="contact-email" href={`mailto:${c.contact.email}`}>{c.contact.email} <i>↗</i></a></section><section className="contact-details"><div><span>{d.businessLabel[l]}</span><a href={`mailto:${c.contact.email}`}>{c.contact.email}</a></div><div><span>{d.locationLabel[l]}</span><p>{d.location[l]}</p></div><div><span>{d.enquiriesLabel[l]}</span><p className="preserve-lines">{d.enquiries[l]}</p></div><div><span>{d.socialLabel[l]}</span><p className="preserve-lines">{d.social}</p></div></section></>}
function Film({c,l}:{c:SiteContent;l:Lang}){const d=c.pages.filmDetail,p=c.featuredProjects[0];return <><section className="crossroads-hero"><div className="crossroads-lines hero-lines"/><p>{d.byline[l]}</p><h1>{p.title}<small>{p.subtitle}</small></h1><div className="film-meta"><span>{p.year}</span><span>{d.genre[l]}</span><span>{d.location[l]}</span></div></section><section className="film-story"><div className="section-label">{d.filmLabel[l]}</div><h2 className="preserve-lines">{p.tagline?.[l]}</h2></section><section className="film-credits"><div className="section-label">{d.creditsLabel[l]}</div>{d.credits.map(x=><div key={x.name}><span>{x.role[l]}</span><strong>{x.name}</strong></div>)}</section><Cta label={d.ctaLabel[l]} text={d.ctaLink[l]} href="/contact"/></>}
function Cta({label,text,href}:{label:string;text:string;href:string}){return <section className="page-cta"><span>{label}</span><Link href={href}>{text} <i>↗</i></Link></section>}
