import {defineArrayMember,defineField,defineType} from 'sanity'
const localized=(name:string,title?:string,group?:string)=>defineField({name,title,type:'localizedString',group})
const localizedList=(name:string)=>defineField({name,type:'array',of:[defineArrayMember({type:'localizedString'})]})
export const siteSettings=defineType({name:'siteSettings',title:'Cài đặt website',type:'document',groups:[
  {name:'general',title:'Thông tin chung',default:true},
  {name:'homepage',title:'Trang chủ'},
  {name:'team',title:'Đội ngũ'},
  {name:'footer',title:'Footer'},
  {name:'pages',title:'Các trang con'},
],fields:[
  defineField({name:'brand',title:'Tên thương hiệu',type:'string',group:'general'}),defineField({name:'brandDescriptor',title:'Mô tả cạnh logo',type:'string',group:'general'}),localized('navMeta','Dòng chữ giữa menu','general'),localized('tagline','Slogan chính','homepage'),localized('supportingLine','Dòng mô tả ngắn','homepage'),localized('positioning','Định vị thương hiệu','general'),
  defineField({name:'navigation',title:'Menu điều hướng',description:'Tên hiển thị trên thanh menu và đường dẫn tương ứng.',type:'array',group:'general',of:[defineArrayMember({type:'object',fields:[localized('label','Tên menu'),defineField({name:'href',title:'Đường dẫn (ví dụ: /about)',type:'string'})]})]}),
  defineField({name:'home',title:'Nội dung các khối trang chủ',description:'Nhãn và tiêu đề cho các phần giới thiệu, dự án và năng lực.',type:'object',group:'homepage',fields:[localized('productionHouse','Dòng giới thiệu đầu trang'),localized('viewProjects','Nút xem dự án'),localized('aboutLink','Nút đi đến Giới thiệu'),localized('featuredLabel','Nhãn dự án nổi bật'),localized('featuredHeading','Tiêu đề dự án nổi bật'),localized('capabilitiesLabel','Nhãn năng lực'),localized('capabilitiesHeading','Tiêu đề năng lực')]}),
  defineField({name:'about',title:'Khối giới thiệu trên trang chủ',type:'object',group:'homepage',fields:[localized('label','Nhãn'),localized('statement','Thông điệp lớn'),localized('footnote','Dòng chú thích')]}),
  defineField({name:'services',title:'Năng lực / Dịch vụ',description:'Mỗi mục sẽ xuất hiện trong phần Năng lực ở trang chủ.',type:'array',group:'homepage',of:[defineArrayMember({type:'object',fields:[localized('title','Tên dịch vụ'),localized('description','Mô tả ngắn')]})]}),
  defineField({name:'contact',title:'Khối liên hệ chung',type:'object',group:'general',fields:[localized('eyebrow','Nhãn liên hệ'),localized('heading','Lời kêu gọi liên hệ'),defineField({name:'email',title:'Email nhận liên hệ',type:'string'})]}),
  defineField({name:'footer',title:'Nội dung Footer',description:'Thông tin hiển thị phía dưới hiệu ứng camera.',type:'object',group:'footer',fields:[localized('availability','Trạng thái nhận dự án'),localized('address','Địa chỉ'),localized('followLabel','Nhãn mạng xã hội'),defineField({name:'socialLinks',title:'Liên kết mạng xã hội',type:'array',of:[defineArrayMember({type:'object',fields:[defineField({name:'label',title:'Tên mạng xã hội',type:'string'}),defineField({name:'href',title:'Đường dẫn',type:'url'})]})]}),localized('copyright','Bản quyền'),localized('topLabel','Nút về đầu trang')]}),
  defineField({name:'teamShowcase',title:'Slideshow đội ngũ',description:'Ảnh được tự chuyển trên trang chủ. Thêm hoặc kéo-thả để đổi thứ tự thành viên.',type:'object',group:'team',fields:[localized('label','Nhãn phần'),localized('heading','Tiêu đề'),defineField({name:'members',title:'Thành viên',type:'array',of:[defineArrayMember({type:'object',fields:[defineField({name:'name',title:'Tên',type:'string'}),localized('role','Vai trò'),defineField({name:'image',title:'Ảnh chân dung',type:'image',options:{hotspot:true}}),defineField({name:'position',title:'Vị trí crop ảnh fallback (ví dụ: 50%)',type:'string'})]})]})]}),
  defineField({name:'pages',title:'Nội dung các trang con',description:'Chỉ chỉnh khi cần thay nội dung trang Dự án, Phim, Giới thiệu và Liên hệ.',type:'object',group:'pages',fields:[
    defineField({name:'work',title:'Trang Dự án',type:'object',fields:[localized('meta'),localized('kicker'),localized('heading'),localizedList('filters'),localized('nextLabel'),localized('nextLink')]}),
    defineField({name:'films',title:'Trang Phim',type:'object',fields:[localized('meta'),localized('kicker'),localized('subKicker'),localized('heading'),localized('intro'),localized('projectGenre'),localized('ctaLabel'),localized('ctaLink')]}),
    defineField({name:'about',title:'Trang Giới thiệu',type:'object',fields:[localized('meta'),localized('kicker'),localized('heading'),localized('heroCopy'),localized('established'),localized('viewpointLabel'),localized('viewpointHeading'),localizedList('paragraphs'),localized('teamLabel'),defineField({name:'team',type:'array',of:[defineArrayMember({type:'object',fields:[defineField({name:'name',type:'string'}),localized('role')]})]}),localized('capabilitiesLabel'),localized('nextLabel'),localized('nextLink')]}),
    defineField({name:'contact',title:'Trang Liên hệ',type:'object',fields:[localized('meta'),localized('availability'),localized('heading'),localized('businessLabel'),localized('locationLabel'),localized('location'),localized('enquiriesLabel'),localized('enquiries'),localized('socialLabel'),defineField({name:'social',type:'text'}),localized('copyright')]}),
    defineField({name:'filmDetail',title:'Trang chi tiết Phim',type:'object',fields:[localized('meta'),localized('byline'),localized('genre'),localized('location'),localized('filmLabel'),localized('creditsLabel'),defineField({name:'credits',type:'array',of:[defineArrayMember({type:'object',fields:[localized('role'),defineField({name:'name',type:'string'})]})]}),localized('ctaLabel'),localized('ctaLink')]}),
  ]}),
]})
